use std::fmt;

/// Errors generated by this crate
#[derive(Debug)]
pub enum Error {
    /// Error serializing/deserializing request, response, or log messages
    Json(serde_json::Error),

    /// Error sending logs
    Http(reqwest::Error),

    /// Error parsing value
    Parse(String),
}

impl std::error::Error for Error {}
unsafe impl Send for Error {}

//impl From<String> for Error {
//    fn from(msg: String) -> Error {
//        Error::Other(msg)
//    }
//}

impl From<serde_json::Error> for Error {
    fn from(e: serde_json::Error) -> Self {
        Error::Json(e)
    }
}

impl From<reqwest::Error> for Error {
    fn from(e: reqwest::Error) -> Self {
        Error::Http(e)
    }
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{:?}", self)
    }
}
